// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "253ff494-4241-4c9b-9296-0da9d610314c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1545979678);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1545979798);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1545980085);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1545974442);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1545974322);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1545974562);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1545983685);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1545979883);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1545974173);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f81a8318-8678-4a83-8836-8eed1f534862}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1545955200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1545979853);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1545989037859");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1545990818859");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1545987077472");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1545990677472");
user_pref("browser.search.region", "GH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181016102217");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1545980061");
user_pref("browser.slowStartup.averageTime", 8016);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20181016102217");
user_pref("browser.startup.homepage_override.mstone", "63.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1545974185171");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "da645dbb9e87401ca183d65d0e52af36");
user_pref("extensions.blocklist.lastModified", "Thu, 27 Dec 2018 16:01:52 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1545979678);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181016102217");
user_pref("extensions.lastAppVersion", "63.0");
user_pref("extensions.lastPlatformVersion", "63.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"7d122705-af5e-47f9-a20b-c8f7ee12ae5f\",\"webcompat@mozilla.org\":\"f040cb8f-57b1-48b8-ab52-751f3a7d74fe\",\"screenshots@mozilla.org\":\"0f845a97-b0b6-47b4-a6f3-81ddab637c3e\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1545980809);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1545974303);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181016102217");
user_pref("media.gmp-manager.lastCheck", 1545974272);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1545980809);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "1166ab25-dbe5-49fa-a2ca-6d8ca89c07b8");
user_pref("services.blocklist.addons.checked", 1545974784);
user_pref("services.blocklist.gfx.checked", 1545974784);
user_pref("services.blocklist.onecrl.checked", 1545974784);
user_pref("services.blocklist.pinning.checked", 1545974784);
user_pref("services.blocklist.plugins.checked", 1545974784);
user_pref("services.settings.clock_skew_seconds", -217);
user_pref("services.settings.last_update_seconds", 1545974784);
user_pref("services.settings.main.tippytop.last_check", 1545974784);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1545980809);
user_pref("toolkit.startup.last_success", 1545980049);
user_pref("toolkit.telemetry.cachedClientID", "9e2c5e61-b09e-4f52-b5c1-fe94589facbd");
user_pref("toolkit.telemetry.previousBuildID", "20181016102217");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
